name: foodie_restaurant
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.3+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.1.0
  flutter_facebook_auth: ^5.0.11
  geoflutterfire2: ^2.3.15
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  place_picker: ^0.10.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  image_gallery_saver: ^1.7.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  intl: ^0.17.0
  multiselect: ^0.1.0
  cached_network_image: ^3.2.3
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^7.4.0
  easy_localization: ^3.0.2
  font_awesome_flutter: ^10.4.0
  photo_view: ^0.14.0
  flutter_native_image: ^0.0.6+1
  the_apple_sign_in: ^1.1.1
  numberpicker: ^2.1.2
  location: ^4.4.0
  dotted_border: ^2.0.0+3
  flutter_facebook_keyhash: ^0.0.4
  datetime_picker_formfield_new: ^2.1.0
  video_player: ^2.6.1
  flutter_sound: ^9.2.13
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  path_provider: ^2.0.15
  sticky_headers: ^0.3.0+2
  barcode_image: ^2.0.2
  image: ^3.1.0
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.6
  dropdown_search: ^5.0.6
  audioplayers: ^4.0.1
  esc_pos_utils:
  bluetooth_thermal_printer:
  flutter_widget_from_html: ^0.10.1
  uuid: ^3.0.7
  flutter_video_info: ^1.3.1
  mime: ^1.0.4
  flutter_rating_bar: ^4.0.1
  flutterflow_paginate_firestore: ^1.0.3+1


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf